const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Platform,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Particles,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.MoveTo.Cnds.IsEnabled,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.MoveTo.Acts.MoveToObject
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{Solid: 0},
	{snow: 0},
	{platforms: 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{Platform: 0},
	{player: 0},
	{Value: 0},
	{gift: 0},
	{gift2: 0},
	{coal: 0},
	{gift3: 0},
	{Santa: 0},
	{Score: 0},
	{Audio: 0},
	{Keyboard: 0},
	{MoveTo: 0},
	{Pathfinding: 0},
	{snowman: 0},
	{particles: 0},
	{snowman2: 0},
	{snowman3: 0},
	{snowman4: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	snow: class extends self.ISpriteInstance {},
	platforms: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	gift: class extends self.ISpriteInstance {},
	gift2: class extends self.ISpriteInstance {},
	coal: class extends self.ISpriteInstance {},
	gift3: class extends self.ISpriteInstance {},
	Santa: class extends self.ISpriteInstance {},
	Score: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	snowman: class extends self.ISpriteInstance {},
	particles: class extends self.IParticlesInstance {},
	snowman2: class extends self.ISpriteInstance {},
	snowman3: class extends self.ISpriteInstance {},
	snowman4: class extends self.ISpriteInstance {}
}